services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
    ports:
      - "5430:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
      - ./data:/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      postgres -c max_connections=1000
              -c shared_buffers=256MB
              -c effective_cache_size=768MB
              -c maintenance_work_mem=64MB
              -c checkpoint_completion_target=0.7
              -c wal_buffers=16MB
              -c default_statistics_target=100
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres_user -d postgres_db" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true
    networks:
      - nifi-net

  nifi:
    image: apache/nifi:1.24.0
    container_name: nifi
    ports:
      - "8080:8080"          # Веб-интерфейс NiFi
      - "8081:8081" # Site-to-Site
    environment:
      - NIFI_CLUSTER_IS_NODE=false
      - NIFI_WEB_HTTPS_PORT=
      - NIFI_WEB_HTTP_HOST=0.0.0.0
      - "8443:8443" 
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_SENSITIVE_PROPS_KEY=Password123!StrongEnough
    volumes:
      - ./nifi_data/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - ./nifi_data/database_repository:/opt/nifi/nifi-current/database_repository
      - ./nifi_data/content_repository:/opt/nifi/nifi-current/content_repository
      - ./nifi_data/provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - ./nifi_data/state:/opt/nifi/nifi-current/state
      - ./nifi_data/logs:/opt/nifi/nifi-current/logs
      - ./postgresql-42.7.3.jar:/opt/nifi/nifi-current/lib/postgresql-42.7.3.jar:ro
      - ./data:/data
    restart: unless-stopped
    networks:
      - nifi-net

volumes:
  pgdata:
    driver: local

networks:
  nifi-net:
    driver: bridge